# Generated by Django 3.1.7 on 2021-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szallodaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_customer',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='login_customer',
            name='table_no',
            field=models.IntegerField(unique=True),
        ),
    ]
