# Generated by Django 3.1.7 on 2021-06-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szallodaapp', '0003_auto_20210613_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_customer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='login_customer',
            name='table_no',
            field=models.CharField(max_length=3),
        ),
    ]
